require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config.ru'
    - 'spec/routing/instruction_spec.rb'
    - 'app/models/user.rb'

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/routing
  Max: 50

Metrics/MethodLength:
  Max: 100
